### ISSUE TITLE
Rename Track

### ISSUE THREAD

**Issue by rpottsoh** [exercism/xpascal#45]
@kytrinyx, @kotp and I have been discussing renaming this track to Delphi Pascal as the exercises are only compatible with Delphi compilers (versions 2010 through Berlin, about 11 versions).  We thought about tackling the rename on our own but we don't know what all is involved beyond altering config.json.  Furthermore, we think it would be a good idea for another "sister" track, catering to the Free Pascal/Lazarus compiler, called Object Pascal.  What do you think about all this?  BTW, I merged the PR for xpascal icon file.

**Comment by jacmoe** [comment]
I am just wondering: why not just call it Delphi?
And then implement regular Pascal (Free Pascal and GNU Pascal) in this repository?
It does not need to require any Lazarus features - it is just a language :)

**Comment by kotp** [comment]
That is a good idea... @kytrinyx would need to review this for client transition path though.  Perhaps the "xPascal" would need to be retired, but it may be in the words to remove the 'x' part of the names in the _near_ future anyway.

**Comment by rpottsoh** [comment]
The test runner used by delphi is not compatible with free pascal and vice versa.   Hiw does one get around this issue with a track called delphi?  Calling the track object Pascal isn't perfect either.  It implies any compiler will work.


Sent from my android device.

**Comment by kotp** [comment]
The idea of calling this track Delphi, I mean, rather than Pascal... They may even avoid the Object Pascal (Delphi, I mean) due to trademark questions... So having the Delphi Programming Language (that quacks like Pascal... ) focused on Delphi things as a track may be appropriate.  Having a FreePascal track... we do so for other tracks, perhaps for different reasons, though.

**Comment by rpottsoh** [comment]
I am totally fine having a separate track(s) that align better with other pascal compilers.  I am a little confused by your last @kotp, are you saying the track should be called delphi or object pascal?

Sent from my android device.

**Comment by kotp** [comment]
I thought that Delphi was avoiding the name "Object Pascal" for trademark potential problems.  I may be wrong in that though.

**Comment by rpottsoh** [comment]
I think there is no issue calling the track Delphi.  The icon I proposed had issues if the track name did not mention Delphi in its name.  I still think Blaise looks cool 😊

Sent from my android device.

**Comment by jacmoe** [comment]
I was kind of disappointed to learn that this track assumes Delphi. :)
Ideally, it should just be Pascal - and people can use GNU Pascal, Free Pascal, whatever.
Isn't there a test framework/runner that can be done in plain Pascal?

Don't get me wrong: my first serious programming endeavour was with Delphi - back in 1997. And I loved it! Because it wasn't Visual Basic, and because my first programming class in the 80's was using Turbo Pascal..
Now, being a Linux guy, that is beyond me. ((And the price tag is also an issue :p))

**Comment by rpottsoh** [comment]
I am not aware of a framework that is universally compatible.  Also there are language divergence issues that make having a single track problematic. 

Sent from my android device.

**Comment by kytrinyx** [comment]
From what I can tell the conclusion is to rename the track to Delphi, and potentially include a second track named Pascal at a later time, if there is enough interest.

Closing in favor of https://github.com/exercism/xpascal/issues/71

**Comment by kotp** [comment]
@jacmoe hopefully you will find some joy in this new track!
